# Generated by Django 6.0.5 on 2026-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.IntegerField(auto_created=True, unique=True)),
                ('Employee_name', models.CharField(max_length=50)),
                ('Employee_email', models.EmailField(max_length=254, unique=True)),
                ('Employee_salary', models.FloatField()),
            ],
        ),
    ]
